import os

USERNAME = os.environ['LZCOINJUPJUP_USERNAME']
PASSWORD = os.environ['LZCOINJUPJUP_PASSWORD']
LOGIN_METHOD = os.environ['LZCOINJUPJUP_LOGIN_METHOD']

FACEBOOK_USERNAME = os.environ['LZCOINJUPJUP_FB_USERNAME']
FACEBOOK_PASSWORD = os.environ['LZCOINJUPJUP_FB_PASSWORD']

TWITTER_USERNAME = os.environ['LZCOINJUPJUP_TT_USERNAME']
TWITTER_PASSWORD = os.environ['LZCOINJUPJUP_TT_PASSWORD']

WAIT_LONG=5
WORK_PERIOD=3600
SHARE_PERIOD=1209600
COLLECT_PERIOD=86400

USERDATA = {
    'USERNAME': USERNAME,
    'PASSWORD':PASSWORD
}

FB_USERDATA = {
    'USERNAME': FACEBOOK_USERNAME,
    'PASSWORD': FACEBOOK_PASSWORD
}

TT_USERDATA = {
    'USERNAME': TWITTER_USERNAME,
    'PASSWORD': TWITTER_PASSWORD
}

FB_POSTMSG = "레진코믹스에서 즐거움을 찾으세요!\n\n\n-Posted by LzCoinJupJup"
